### PR TITLE
updates

### PR DESCRIPTION
**Pull request by aviatesk**
Will use Documenter.jl v0.24.0.

I would also like to tag a new "stable" release, but not sure how to do. Any advice for that ?

### CODE REVIEW

**Comment by pfitzseb** [comment]
Stable is updated when we tag a new release in this repo.

**Comment by aviatesk** [comment]
okay, can I patch-tagging ?

**Comment by pfitzseb** [comment]
I already tagged 0.11.1.

**Comment by aviatesk** [comment]
cool :)

**Pull request merged**
